[feat] Place Card 구현
TeamDATEROAD/DATEROAD-ANDROID pull request #30
Opened 2024-07-07 15:14 UTC by t1nm1ksun

## Related issue 🛠
- closed #29 

## Work Description ✏️
- Tag를 이용해 Place Card 구현

## Screenshot 📸
<img width="390" alt="image" src="https://github.com/TeamDATEROAD/DATEROAD-ANDROID/assets/122257945/bda8b9c5-f240-44b0-b03d-6a4f96bb0fb2">

## Uncompleted Tasks 😅
- 없습니다!

## To Reviewers 📢

2024-07-07 19:51 UTC, 2hyunjinn requested changes
공통 컴포넌트 구현하느라 고생 많으셨어요-! 😎👍🏻👍🏻

2024-07-07 19:51 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    }
```suggestion
Column {
        DateRoadPlaceCard(
            timeline= "1",
            text = "성수미술관 성수점",
            time = "2시간"
        )
    }
```
인자 값을 좀 더 명확하게 표현하는게 좋을 것 같아요!

2024-07-07 19:51 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    }
```suggestion
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(14.dp))
            .background(DateRoadTheme.colors.gray100)
            .padding(horizontal = 14.dp, vertical = 13.dp),
        horizontalArrangement = Arrangement.Center,
        verticalAlignment = Alignment.CenterVertically
    ) {
        DateRoadTextTag(
            textContent = timeline,
            tagContentType = TagType.PLACE_CARD_NUMBER
        )
        Spacer(modifier = Modifier.width(14.dp))
        Text(
            text = text,
            modifier = Modifier.weight(1f),
            style = DateRoadTheme.typography.bodyBold15
        )
        DateRoadTextTag(
            textContent = time,
            tagContentType = TagType.PLACE_CARD_TIME
        )
    }
```

Row를 두 번 쓸 필요가 없는 것 같아요! 혹시 따로 두 번 쓰신 이유가 있을까요?
그리고 중간에 불필요한 Spacer가 있는 것 같아서 확인 부탁드려요!

2024-07-08 02:38 UTC, jihyunniiii reviewed
고생하셨습니다 ~

2024-07-08 02:38 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
타입 만들어서 분기처리 진행해주세요,, 컴포넌트 네이밍은,, 기깔나는 걸로 부탁드려요
타입 네이밍은 PLACE_CARD, COURSE_NORMAL, COURSE_EDIT 정도로 하면 될 것 같네요

2024-07-08 02:38 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    ) {
시간 태그 기준으로 패딩 처리 해야할 것 같아용

2024-07-08 06:00 UTC, jihyunniiii approved these changes
터치 영역만 추가해 주시고 리뷰 반영만 해주세용 잘했당 ~

2024-07-08 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +        Modifier.padding(start = 17.dp, end = 19.dp)
얘까지 타입화 진행하면 좋을 듯요?

2024-07-08 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    placeTime: String
이거 아까 설계한 entity로 진행해주시와요

2024-07-08 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +            Spacer(modifier = Modifier.width(10.dp))
10 -> 14

2024-07-08 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +            style = DateRoadTheme.typography.bodyBold15
textColor 추가해 주세용

2024-07-08 06:00 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +        )
Text와 Tag 사이에 10 간격 추가

2024-07-08 11:35 UTC, 2hyunjinn requested changes

2024-07-08 11:35 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    place: Place,
이거 Entity로 받아와야 하는 거 아닌가요!

2024-07-08 11:37 UTC, t1nm1ksun commented on app/src/main/java/org/sopt/dateroad/presentation/ui/component/placecard/DateRoadPlaceCard.kt
> +    place: Place,
place가 Entity고 TImeline은 index값 따로 받아오기로 했습니다!

2024-07-08 12:58 UTC, 2hyunjinn approved these changes

2024-07-08 13:06 UTC, merged