[feat] 코스 등록하기 (Enroll) 컴포넌트 구현
TeamDATEROAD/DATEROAD-ANDROID pull request #63
Opened 2024-07-09 11:46 UTC by jihyunniiii

## Related issue 🛠
- closed #57 

## Work Description ✏️
- 코스 등록하기 (Enroll) 컴포넌트를 구현했어요.

## Screenshot 📸
- 장소명 입력

https://github.com/TeamDATEROAD/DATEROAD-ANDROID/assets/103172971/997dfb22-ce88-4454-86c7-7d964a106aba

- 이미지 미리보기

https://github.com/TeamDATEROAD/DATEROAD-ANDROID/assets/103172971/eea86f0d-6f74-4fa1-afc5-c21229f9d0d0

## Uncompleted Tasks 😅
- N/A

## To Reviewers 📢
컴포넌트 끝났습니당 ㅠ 늦게 끝내서 죄송합니다 ㅠㅠ

2024-07-09 16:13 UTC, 2hyunjinn requested changes
고생 많으셨어용~

2024-07-09 16:13 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +        Spacer(modifier = Modifier.width(8.dp))
이거 지우고
horizontalArrangement = Arrangement.spacedBy(8.dp)
Row()안에 이거 주는 건 어떨까요?

2024-07-09 16:13 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +                .padding(vertical = 16.dp)
12였는데... 잘 합의해보시길...

2024-07-09 16:13 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +        Spacer(modifier = Modifier.width(8.dp))
이것도 위의 리뷰랑 똑같습니다!

2024-07-09 16:13 UTC, 2hyunjinn commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +            paddingHorizontal = 15.dp,
이것도 12... 인데....

2024-07-10 09:02 UTC, t1nm1ksun approved these changes
와 엄청 고생했겠다..!

2024-07-10 09:02 UTC, t1nm1ksun commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotos.kt
> +            textContent = stringResource(id = R.string.fraction_format, images.size, 10),
stringResource 인자 중에 id 말고 다른것도 있는지 몰랐어요! 뒤에 두개는 사이즈와 관련되어있는 건가요?

2024-07-10 09:02 UTC, t1nm1ksun commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +    val density = LocalDensity.current
context처럼 생긴 이놈은 먼가요!?

2024-07-10 09:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +        Spacer(modifier = Modifier.width(8.dp))
천재 아니세요?

2024-07-10 09:07 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPlaceInsertBar.kt
> +                .padding(vertical = 16.dp)
합의 보았습니다 어프룹 해주세요 ㅎ.ㅎ

2024-07-10 12:08 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollAddPhotoButton.kt
> +) {
추후에 Modifier에 대한 값들을 조절해야 하는 경우가 많은 것 같아서 (패딩 등등) 저는 개인적으로 넣어주는 게 좋은 것 같아요

2024-07-10 12:08 UTC, jihyunniiii commented on app/src/main/java/org/sopt/dateroad/presentation/ui/enroll/component/EnrollPhotos.kt
> +            textContent = stringResource(id = R.string.fraction_format, images.size, 10),
ㅋㅋ 신민석 당장 컴온

2024-07-10 15:32 UTC, 2hyunjinn approved these changes

2024-07-10 15:33 UTC, merged